# Database configurations
database:
  driver: postgres
  dbname: postgres
  host: localhost
  port: 5432
  idleConns: 2
  openConns: 10
  schema: "lumel"
  username: "postgres"
  password: "postgres"

#path for csv file
csv:
  path: "sample.csv"
  